// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.4.0
// Machine:  VOSTRO
// DateTime: 2/18/2012 3:05:22 PM
// UserName: Tim
// Input file <..\GeneratorInputFiles\tranche.y>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using LexicalAnalysis;
using AbstractSyntaxTree;
using AbstractSyntaxTree.InternalTypes;
using tc;

namespace SyntaxAnalysis
{
internal enum Tokens {
    error=1,EOF=2,SETTINGS=3,DEAL=4,COLLATERAL=5,COLLATERALITEM=6,
    SECURITIES=7,BOND=8,CREDITPAYMENTRULES=9,SIMULATION=10,RULES=11,RPAREN=12,
    LBRACE=13,RBRACE=14,RBRACKET=15,PBRACKET=16,DOT=17,DOTDOT=18,
    COMMA=19,IN=20,TINT=21,TREAL=22,SEMI=23,INTEREST=24,
    TSTRING=25,TBOOL=26,TVOID=27,TCHAR=28,TFILE=29,TSET=30,
    TLIST=31,FOR=32,IF=33,ELSE=34,CLASS=35,AUTOPROP=36,
    PRINCIPAL=37,RULE=38,NEW=39,RETURN=40,TRUE=41,FALSE=42,
    LITERAL_INT=43,LITERAL_REAL=44,LITERAL_STRING=45,LITERAL_CHAR=46,IDENTIFIER=47,ASSIGN=48,
    OR=49,AND=50,INCREMENT=51,DECREMENT=52,EXP=53,SMALLER=54,
    GREATER=55,SMEQ=56,GTEQ=57,EQ=58,NEQ=59,PLUS=60,
    MINUS=61,TIMES=62,DIVIDE=63,MOD=64,UMINUS=65,LPAREN=66,
    NOT=67,LBRACKET=68};

// Abstract base class for GPLEX scanners
internal abstract class ScanBase : AbstractScanner<SemanticValue,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

internal class Parser: ShiftReduceParser<SemanticValue, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[52];
  private static State[] states = new State[107];
  private static string[] nonTerms = new string[] {
      "program", "statementList", "statement", "expression", "literal", "compExpression", 
      "lvalue", "onePlusActuals", "actuals", "boolListOpt", "settingsOpt", "dealOpt", 
      "collateralSection", "securitySection", "simulationSection", "secListOpt", 
      "creditRulesOpt", "rulesListOpt", "collListOpt", "interestRules", "principalRules", 
      "$accept", };

  static Parser() {
    states[0] = new State(new int[]{3,103,4,-3,5,-3},new int[]{-1,1,-11,3});
    states[1] = new State(new int[]{2,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{4,99,5,-5},new int[]{-12,4});
    states[4] = new State(new int[]{5,90},new int[]{-13,5});
    states[5] = new State(new int[]{7,81},new int[]{-14,6});
    states[6] = new State(new int[]{9,57,10,-15},new int[]{-17,7});
    states[7] = new State(new int[]{10,9},new int[]{-15,8});
    states[8] = new State(-2);
    states[9] = new State(new int[]{13,10});
    states[10] = new State(new int[]{47,15,13,48,33,51,43,39,44,40,45,41,41,42,42,43,14,-7},new int[]{-2,11,-3,13,-4,56,-5,38,-6,44,-7,45});
    states[11] = new State(new int[]{14,12});
    states[12] = new State(-26);
    states[13] = new State(new int[]{47,15,13,48,33,51,43,39,44,40,45,41,41,42,42,43,14,-7},new int[]{-2,14,-3,13,-4,56,-5,38,-6,44,-7,45});
    states[14] = new State(-8);
    states[15] = new State(new int[]{48,16,66,31,17,-35,58,-35,59,-35,56,-35,57,-35,55,-35,54,-35,47,-35,13,-35,33,-35,43,-35,44,-35,45,-35,41,-35,42,-35,14,-35});
    states[16] = new State(new int[]{47,30,43,39,44,40,45,41,41,42,42,43},new int[]{-4,17,-5,38,-6,44,-7,45});
    states[17] = new State(new int[]{58,18,59,20,56,22,57,24,55,26,54,28,47,-9,13,-9,33,-9,43,-9,44,-9,45,-9,41,-9,42,-9,14,-9});
    states[18] = new State(new int[]{47,30,43,39,44,40,45,41,41,42,42,43},new int[]{-4,19,-5,38,-6,44,-7,45});
    states[19] = new State(-37);
    states[20] = new State(new int[]{47,30,43,39,44,40,45,41,41,42,42,43},new int[]{-4,21,-5,38,-6,44,-7,45});
    states[21] = new State(-38);
    states[22] = new State(new int[]{47,30,43,39,44,40,45,41,41,42,42,43},new int[]{-4,23,-5,38,-6,44,-7,45});
    states[23] = new State(-39);
    states[24] = new State(new int[]{47,30,43,39,44,40,45,41,41,42,42,43},new int[]{-4,25,-5,38,-6,44,-7,45});
    states[25] = new State(-40);
    states[26] = new State(new int[]{47,30,43,39,44,40,45,41,41,42,42,43},new int[]{-4,27,-5,38,-6,44,-7,45});
    states[27] = new State(-41);
    states[28] = new State(new int[]{47,30,43,39,44,40,45,41,41,42,42,43},new int[]{-4,29,-5,38,-6,44,-7,45});
    states[29] = new State(-42);
    states[30] = new State(new int[]{66,31,17,-35,58,-35,59,-35,56,-35,57,-35,55,-35,54,-35,47,-35,13,-35,33,-35,43,-35,44,-35,45,-35,41,-35,42,-35,14,-35,19,-35,12,-35,38,-35,49,-35,50,-35});
    states[31] = new State(new int[]{47,30,43,39,44,40,45,41,41,42,42,43,12,-43},new int[]{-9,32,-8,34,-4,35,-5,38,-6,44,-7,45});
    states[32] = new State(new int[]{12,33});
    states[33] = new State(-31);
    states[34] = new State(-44);
    states[35] = new State(new int[]{58,18,59,20,56,22,57,24,55,26,54,28,19,36,12,-45});
    states[36] = new State(new int[]{47,30,43,39,44,40,45,41,41,42,42,43,12,-43},new int[]{-9,37,-8,34,-4,35,-5,38,-6,44,-7,45});
    states[37] = new State(-46);
    states[38] = new State(-32);
    states[39] = new State(-47);
    states[40] = new State(-48);
    states[41] = new State(-49);
    states[42] = new State(-50);
    states[43] = new State(-51);
    states[44] = new State(-33);
    states[45] = new State(new int[]{17,46,58,-34,59,-34,56,-34,57,-34,55,-34,54,-34,47,-34,13,-34,33,-34,43,-34,44,-34,45,-34,41,-34,42,-34,14,-34,19,-34,12,-34,38,-34,49,-34,50,-34});
    states[46] = new State(new int[]{47,47});
    states[47] = new State(-36);
    states[48] = new State(new int[]{47,15,13,48,33,51,43,39,44,40,45,41,41,42,42,43,14,-7},new int[]{-2,49,-3,13,-4,56,-5,38,-6,44,-7,45});
    states[49] = new State(new int[]{14,50});
    states[50] = new State(-10);
    states[51] = new State(new int[]{66,52});
    states[52] = new State(new int[]{47,30,43,39,44,40,45,41,41,42,42,43},new int[]{-4,53,-5,38,-6,44,-7,45});
    states[53] = new State(new int[]{12,54,58,18,59,20,56,22,57,24,55,26,54,28});
    states[54] = new State(new int[]{47,15,13,48,33,51,43,39,44,40,45,41,41,42,42,43},new int[]{-3,55,-4,56,-5,38,-6,44,-7,45});
    states[55] = new State(-11);
    states[56] = new State(new int[]{58,18,59,20,56,22,57,24,55,26,54,28,47,-12,13,-12,33,-12,43,-12,44,-12,45,-12,41,-12,42,-12,14,-12});
    states[57] = new State(new int[]{13,58});
    states[58] = new State(new int[]{24,77,37,-17,14,-17},new int[]{-20,59});
    states[59] = new State(new int[]{37,62,14,-19},new int[]{-21,60});
    states[60] = new State(new int[]{14,61});
    states[61] = new State(-16);
    states[62] = new State(new int[]{13,63});
    states[63] = new State(new int[]{38,66,14,-21},new int[]{-18,64});
    states[64] = new State(new int[]{14,65});
    states[65] = new State(-20);
    states[66] = new State(new int[]{47,30,43,39,44,40,45,41,41,42,42,43},new int[]{-6,67,-4,76,-5,38,-7,45});
    states[67] = new State(new int[]{38,66,49,70,50,73,58,-33,59,-33,56,-33,57,-33,55,-33,54,-33,14,-21},new int[]{-10,68,-18,69});
    states[68] = new State(-22);
    states[69] = new State(-23);
    states[70] = new State(new int[]{47,30,43,39,44,40,45,41,41,42,42,43},new int[]{-6,71,-4,76,-5,38,-7,45});
    states[71] = new State(new int[]{38,66,49,70,50,73,58,-33,59,-33,56,-33,57,-33,55,-33,54,-33,14,-21},new int[]{-10,72,-18,69});
    states[72] = new State(-24);
    states[73] = new State(new int[]{47,30,43,39,44,40,45,41,41,42,42,43},new int[]{-6,74,-4,76,-5,38,-7,45});
    states[74] = new State(new int[]{38,66,49,70,50,73,58,-33,59,-33,56,-33,57,-33,55,-33,54,-33,14,-21},new int[]{-10,75,-18,69});
    states[75] = new State(-25);
    states[76] = new State(new int[]{58,18,59,20,56,22,57,24,55,26,54,28});
    states[77] = new State(new int[]{13,78});
    states[78] = new State(new int[]{38,66,14,-21},new int[]{-18,79});
    states[79] = new State(new int[]{14,80});
    states[80] = new State(-18);
    states[81] = new State(new int[]{13,82});
    states[82] = new State(new int[]{8,85,14,-29},new int[]{-16,83});
    states[83] = new State(new int[]{14,84});
    states[84] = new State(-14);
    states[85] = new State(new int[]{13,86});
    states[86] = new State(new int[]{47,15,13,48,33,51,43,39,44,40,45,41,41,42,42,43,14,-7},new int[]{-2,87,-3,13,-4,56,-5,38,-6,44,-7,45});
    states[87] = new State(new int[]{14,88});
    states[88] = new State(new int[]{8,85,14,-29},new int[]{-16,89});
    states[89] = new State(-30);
    states[90] = new State(new int[]{13,91});
    states[91] = new State(new int[]{6,94,14,-27},new int[]{-19,92});
    states[92] = new State(new int[]{14,93});
    states[93] = new State(-13);
    states[94] = new State(new int[]{13,95});
    states[95] = new State(new int[]{47,15,13,48,33,51,43,39,44,40,45,41,41,42,42,43,14,-7},new int[]{-2,96,-3,13,-4,56,-5,38,-6,44,-7,45});
    states[96] = new State(new int[]{14,97});
    states[97] = new State(new int[]{6,94,14,-27},new int[]{-19,98});
    states[98] = new State(-28);
    states[99] = new State(new int[]{13,100});
    states[100] = new State(new int[]{47,15,13,48,33,51,43,39,44,40,45,41,41,42,42,43,14,-7},new int[]{-2,101,-3,13,-4,56,-5,38,-6,44,-7,45});
    states[101] = new State(new int[]{14,102});
    states[102] = new State(-6);
    states[103] = new State(new int[]{13,104});
    states[104] = new State(new int[]{47,15,13,48,33,51,43,39,44,40,45,41,41,42,42,43,14,-7},new int[]{-2,105,-3,13,-4,56,-5,38,-6,44,-7,45});
    states[105] = new State(new int[]{14,106});
    states[106] = new State(-4);

    rules[1] = new Rule(-22, new int[]{-1,2});
    rules[2] = new Rule(-1, new int[]{-11,-12,-13,-14,-17,-15});
    rules[3] = new Rule(-11, new int[]{});
    rules[4] = new Rule(-11, new int[]{3,13,-2,14});
    rules[5] = new Rule(-12, new int[]{});
    rules[6] = new Rule(-12, new int[]{4,13,-2,14});
    rules[7] = new Rule(-2, new int[]{});
    rules[8] = new Rule(-2, new int[]{-3,-2});
    rules[9] = new Rule(-3, new int[]{47,48,-4});
    rules[10] = new Rule(-3, new int[]{13,-2,14});
    rules[11] = new Rule(-3, new int[]{33,66,-4,12,-3});
    rules[12] = new Rule(-3, new int[]{-4});
    rules[13] = new Rule(-13, new int[]{5,13,-19,14});
    rules[14] = new Rule(-14, new int[]{7,13,-16,14});
    rules[15] = new Rule(-17, new int[]{});
    rules[16] = new Rule(-17, new int[]{9,13,-20,-21,14});
    rules[17] = new Rule(-20, new int[]{});
    rules[18] = new Rule(-20, new int[]{24,13,-18,14});
    rules[19] = new Rule(-21, new int[]{});
    rules[20] = new Rule(-21, new int[]{37,13,-18,14});
    rules[21] = new Rule(-18, new int[]{});
    rules[22] = new Rule(-18, new int[]{38,-6,-10});
    rules[23] = new Rule(-10, new int[]{-18});
    rules[24] = new Rule(-10, new int[]{49,-6,-10});
    rules[25] = new Rule(-10, new int[]{50,-6,-10});
    rules[26] = new Rule(-15, new int[]{10,13,-2,14});
    rules[27] = new Rule(-19, new int[]{});
    rules[28] = new Rule(-19, new int[]{6,13,-2,14,-19});
    rules[29] = new Rule(-16, new int[]{});
    rules[30] = new Rule(-16, new int[]{8,13,-2,14,-16});
    rules[31] = new Rule(-4, new int[]{47,66,-9,12});
    rules[32] = new Rule(-4, new int[]{-5});
    rules[33] = new Rule(-4, new int[]{-6});
    rules[34] = new Rule(-4, new int[]{-7});
    rules[35] = new Rule(-7, new int[]{47});
    rules[36] = new Rule(-7, new int[]{-7,17,47});
    rules[37] = new Rule(-6, new int[]{-4,58,-4});
    rules[38] = new Rule(-6, new int[]{-4,59,-4});
    rules[39] = new Rule(-6, new int[]{-4,56,-4});
    rules[40] = new Rule(-6, new int[]{-4,57,-4});
    rules[41] = new Rule(-6, new int[]{-4,55,-4});
    rules[42] = new Rule(-6, new int[]{-4,54,-4});
    rules[43] = new Rule(-9, new int[]{});
    rules[44] = new Rule(-9, new int[]{-8});
    rules[45] = new Rule(-8, new int[]{-4});
    rules[46] = new Rule(-8, new int[]{-4,19,-9});
    rules[47] = new Rule(-5, new int[]{43});
    rules[48] = new Rule(-5, new int[]{44});
    rules[49] = new Rule(-5, new int[]{45});
    rules[50] = new Rule(-5, new int[]{41});
    rules[51] = new Rule(-5, new int[]{42});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
    switch (action)
    {
      case 2: // program -> settingsOpt, dealOpt, collateralSection, securitySection, 
              //            creditRulesOpt, simulationSection
{ CurrentSemanticValue.Prog = new Prog(ValueStack[ValueStack.Depth-6].DeclarationClass, ValueStack[ValueStack.Depth-5].DeclarationClass, ValueStack[ValueStack.Depth-4].DeclarationClass, ValueStack[ValueStack.Depth-3].DeclarationClass, ValueStack[ValueStack.Depth-2].DeclarationClass, ValueStack[ValueStack.Depth-1].DeclarationClass); SyntaxTreeRoot = CurrentSemanticValue.Prog; CurrentSemanticValue.Prog.Location = CurrentLocationSpan; }
        break;
      case 3: // settingsOpt -> /* empty */
{ CurrentSemanticValue.DeclarationClass = new Settings(); CurrentSemanticValue.DeclarationClass.Location = CurrentLocationSpan; }
        break;
      case 4: // settingsOpt -> SETTINGS, LBRACE, statementList, RBRACE
{ CurrentSemanticValue.DeclarationClass = new Settings(ValueStack[ValueStack.Depth-2].StatementList);  }
        break;
      case 5: // dealOpt -> /* empty */
{ CurrentSemanticValue.DeclarationClass = new Deal(); CurrentSemanticValue.DeclarationClass.Location = CurrentLocationSpan; }
        break;
      case 6: // dealOpt -> DEAL, LBRACE, statementList, RBRACE
{ CurrentSemanticValue.DeclarationClass = new Deal(ValueStack[ValueStack.Depth-2].StatementList); CurrentSemanticValue.DeclarationClass.Location = CurrentLocationSpan; }
        break;
      case 7: // statementList -> /* empty */
{ CurrentSemanticValue.StatementList = new StatementList(); CurrentSemanticValue.StatementList.Location = CurrentLocationSpan; }
        break;
      case 8: // statementList -> statement, statementList
{ CurrentSemanticValue.StatementList = new StatementList(ValueStack[ValueStack.Depth-2].Statement, ValueStack[ValueStack.Depth-1].StatementList); CurrentSemanticValue.StatementList.Location = CurrentLocationSpan; }
        break;
      case 9: // statement -> IDENTIFIER, ASSIGN, expression
{ CurrentSemanticValue.Statement = new Assign(new Identifier(CurrentLocationSpan, ValueStack[ValueStack.Depth-3].Token.Value), ValueStack[ValueStack.Depth-1].Expression); CurrentSemanticValue.Statement.Location = CurrentLocationSpan; }
        break;
      case 10: // statement -> LBRACE, statementList, RBRACE
{ CurrentSemanticValue.Statement = new Block(ValueStack[ValueStack.Depth-2].StatementList); CurrentSemanticValue.Statement.Location = CurrentLocationSpan; }
        break;
      case 11: // statement -> IF, LPAREN, expression, RPAREN, statement
{ CurrentSemanticValue.Statement = new IfThen(ValueStack[ValueStack.Depth-3].Expression, ValueStack[ValueStack.Depth-1].Statement); CurrentSemanticValue.Statement.Location = CurrentLocationSpan; }
        break;
      case 12: // statement -> expression
{ CurrentSemanticValue.Statement = new StatementExpression(ValueStack[ValueStack.Depth-1].Expression); CurrentSemanticValue.Statement.Location = CurrentLocationSpan; }
        break;
      case 13: // collateralSection -> COLLATERAL, LBRACE, collListOpt, RBRACE
{ CurrentSemanticValue.DeclarationClass = new Collateral(ValueStack[ValueStack.Depth-2].CollateralItem); CurrentSemanticValue.DeclarationClass.Location = CurrentLocationSpan; }
        break;
      case 14: // securitySection -> SECURITIES, LBRACE, secListOpt, RBRACE
{ CurrentSemanticValue.DeclarationClass = new Securities(ValueStack[ValueStack.Depth-2].Bond); CurrentSemanticValue.DeclarationClass.Location = CurrentLocationSpan; }
        break;
      case 15: // creditRulesOpt -> /* empty */
{ CurrentSemanticValue.DeclarationClass = new CreditPaymentRules(); CurrentSemanticValue.DeclarationClass.Location = CurrentLocationSpan; }
        break;
      case 16: // creditRulesOpt -> CREDITPAYMENTRULES, LBRACE, interestRules, principalRules, 
               //                   RBRACE
{ CurrentSemanticValue.DeclarationClass = new CreditPaymentRules(new StatementList(ValueStack[ValueStack.Depth-3].InterestRules,ValueStack[ValueStack.Depth-2].PrincipalRules)); CurrentSemanticValue.DeclarationClass.Location = CurrentLocationSpan; }
        break;
      case 17: // interestRules -> /* empty */
{ CurrentSemanticValue.InterestRules = new InterestRules(); CurrentSemanticValue.InterestRules.Location = CurrentLocationSpan; }
        break;
      case 18: // interestRules -> INTEREST, LBRACE, rulesListOpt, RBRACE
{ CurrentSemanticValue.InterestRules = new InterestRules(ValueStack[ValueStack.Depth-2].InternalRuleList); CurrentSemanticValue.InterestRules.Location = CurrentLocationSpan; }
        break;
      case 19: // principalRules -> /* empty */
{ CurrentSemanticValue.PrincipalRules =  new PrincipalRules(); CurrentSemanticValue.PrincipalRules.Location = CurrentLocationSpan; }
        break;
      case 20: // principalRules -> PRINCIPAL, LBRACE, rulesListOpt, RBRACE
{ CurrentSemanticValue.PrincipalRules =  new PrincipalRules(ValueStack[ValueStack.Depth-2].InternalRuleList); CurrentSemanticValue.PrincipalRules.Location = CurrentLocationSpan; }
        break;
      case 21: // rulesListOpt -> /* empty */
{ CurrentSemanticValue.InternalRuleList = new InternalRuleList(); CurrentSemanticValue.InternalRuleList.Location = CurrentLocationSpan; }
        break;
      case 22: // rulesListOpt -> RULE, compExpression, boolListOpt
{ CurrentSemanticValue.InternalRuleList = new InternalRuleList(ValueStack[ValueStack.Depth-2].Expression, ValueStack[ValueStack.Depth-1].ExpressionList); CurrentSemanticValue.InternalRuleList.Location = CurrentLocationSpan; }
        break;
      case 23: // boolListOpt -> rulesListOpt
{ CurrentSemanticValue.ExpressionList = ValueStack[ValueStack.Depth-1].InternalRuleList; CurrentSemanticValue.ExpressionList.Location = CurrentLocationSpan; }
        break;
      case 24: // boolListOpt -> OR, compExpression, boolListOpt
{ CurrentSemanticValue.ExpressionList = new InternalRuleListOr(ValueStack[ValueStack.Depth-2].Expression, ValueStack[ValueStack.Depth-1].ExpressionList); CurrentSemanticValue.ExpressionList.Location = CurrentLocationSpan;  }
        break;
      case 25: // boolListOpt -> AND, compExpression, boolListOpt
{ CurrentSemanticValue.ExpressionList = new InternalRuleListAnd(ValueStack[ValueStack.Depth-2].Expression, ValueStack[ValueStack.Depth-1].ExpressionList); CurrentSemanticValue.ExpressionList.Location = CurrentLocationSpan; }
        break;
      case 26: // simulationSection -> SIMULATION, LBRACE, statementList, RBRACE
{ CurrentSemanticValue.DeclarationClass = new Simulation(ValueStack[ValueStack.Depth-2].StatementList); CurrentSemanticValue.DeclarationClass.Location = CurrentLocationSpan; }
        break;
      case 27: // collListOpt -> /* empty */
{ CurrentSemanticValue.CollateralItem = new CollateralItem(); CurrentSemanticValue.CollateralItem.Location = CurrentLocationSpan; }
        break;
      case 28: // collListOpt -> COLLATERALITEM, LBRACE, statementList, RBRACE, collListOpt
{ CurrentSemanticValue.CollateralItem = new CollateralItem(ValueStack[ValueStack.Depth-3].StatementList, ValueStack[ValueStack.Depth-1].CollateralItem); CurrentSemanticValue.CollateralItem.Location = CurrentLocationSpan; }
        break;
      case 29: // secListOpt -> /* empty */
{ CurrentSemanticValue.Bond = new Bond(); CurrentSemanticValue.Bond.Location = CurrentLocationSpan; }
        break;
      case 30: // secListOpt -> BOND, LBRACE, statementList, RBRACE, secListOpt
{ CurrentSemanticValue.Bond = new Bond(ValueStack[ValueStack.Depth-3].StatementList, ValueStack[ValueStack.Depth-1].Bond); CurrentSemanticValue.Bond.Location = CurrentLocationSpan; }
        break;
      case 31: // expression -> IDENTIFIER, LPAREN, actuals, RPAREN
{ CurrentSemanticValue.Expression = new Invoke(ValueStack[ValueStack.Depth-4].Token.Value, ValueStack[ValueStack.Depth-2].ExpressionList); CurrentSemanticValue.Expression.Location = CurrentLocationSpan; }
        break;
      case 32: // expression -> literal
{ CurrentSemanticValue.Expression = ValueStack[ValueStack.Depth-1].Expression; CurrentSemanticValue.Expression.Location = CurrentLocationSpan; }
        break;
      case 33: // expression -> compExpression
{ CurrentSemanticValue.Expression = ValueStack[ValueStack.Depth-1].Expression; CurrentSemanticValue.Expression.Location = CurrentLocationSpan; }
        break;
      case 34: // expression -> lvalue
{ CurrentSemanticValue.Expression = ValueStack[ValueStack.Depth-1].Expression; CurrentSemanticValue.Expression.Location = CurrentLocationSpan; }
        break;
      case 35: // lvalue -> IDENTIFIER
{ CurrentSemanticValue.Expression = new Identifier(CurrentLocationSpan, ValueStack[ValueStack.Depth-1].Token.Value); CurrentSemanticValue.Expression.Location = CurrentLocationSpan; }
        break;
      case 36: // lvalue -> lvalue, DOT, IDENTIFIER
{ CurrentSemanticValue.Expression = new DereferenceField(ValueStack[ValueStack.Depth-3].Expression, ValueStack[ValueStack.Depth-1].Token.Value); CurrentSemanticValue.Expression.Location = CurrentLocationSpan; }
        break;
      case 37: // compExpression -> expression, EQ, expression
{ CurrentSemanticValue.Expression = new Equal(ValueStack[ValueStack.Depth-3].Expression, ValueStack[ValueStack.Depth-1].Expression); CurrentSemanticValue.Expression.Location = CurrentLocationSpan; }
        break;
      case 38: // compExpression -> expression, NEQ, expression
{ CurrentSemanticValue.Expression = new NotEqual(ValueStack[ValueStack.Depth-3].Expression, ValueStack[ValueStack.Depth-1].Expression); CurrentSemanticValue.Expression.Location = CurrentLocationSpan; }
        break;
      case 39: // compExpression -> expression, SMEQ, expression
{ CurrentSemanticValue.Expression = new SmallerEqual(ValueStack[ValueStack.Depth-3].Expression, ValueStack[ValueStack.Depth-1].Expression); CurrentSemanticValue.Expression.Location = CurrentLocationSpan; }
        break;
      case 40: // compExpression -> expression, GTEQ, expression
{ CurrentSemanticValue.Expression = new GreaterEqual(ValueStack[ValueStack.Depth-3].Expression, ValueStack[ValueStack.Depth-1].Expression); CurrentSemanticValue.Expression.Location = CurrentLocationSpan; }
        break;
      case 41: // compExpression -> expression, GREATER, expression
{ CurrentSemanticValue.Expression = new Greater(ValueStack[ValueStack.Depth-3].Expression, ValueStack[ValueStack.Depth-1].Expression); CurrentSemanticValue.Expression.Location = CurrentLocationSpan; }
        break;
      case 42: // compExpression -> expression, SMALLER, expression
{ CurrentSemanticValue.Expression = new Smaller(ValueStack[ValueStack.Depth-3].Expression, ValueStack[ValueStack.Depth-1].Expression); CurrentSemanticValue.Expression.Location = CurrentLocationSpan; }
        break;
      case 43: // actuals -> /* empty */
{ CurrentSemanticValue.ExpressionList = new ExpressionList(); CurrentSemanticValue.ExpressionList.Location = CurrentLocationSpan; }
        break;
      case 44: // actuals -> onePlusActuals
{ CurrentSemanticValue.ExpressionList = ValueStack[ValueStack.Depth-1].ExpressionList; CurrentSemanticValue.ExpressionList.Location = CurrentLocationSpan; }
        break;
      case 45: // onePlusActuals -> expression
{ CurrentSemanticValue.ExpressionList = new ExpressionList(ValueStack[ValueStack.Depth-1].Expression, new ExpressionList()); CurrentSemanticValue.ExpressionList.Location = CurrentLocationSpan; }
        break;
      case 46: // onePlusActuals -> expression, COMMA, actuals
{ CurrentSemanticValue.ExpressionList = new ExpressionList(ValueStack[ValueStack.Depth-3].Expression, ValueStack[ValueStack.Depth-1].ExpressionList); CurrentSemanticValue.ExpressionList.Location = CurrentLocationSpan; }
        break;
      case 47: // literal -> LITERAL_INT
{ CurrentSemanticValue.Expression = new IntegerLiteral(Int32.Parse(ValueStack[ValueStack.Depth-1].Token.Value.ToString().Replace(",",""))); CurrentSemanticValue.Expression.Location = CurrentLocationSpan; }
        break;
      case 48: // literal -> LITERAL_REAL
{ CurrentSemanticValue.Expression = new RealLiteral(Double.Parse(ValueStack[ValueStack.Depth-1].Token.Value.ToString().Replace(",",""))); CurrentSemanticValue.Expression.Location = CurrentLocationSpan; }
        break;
      case 49: // literal -> LITERAL_STRING
{ CurrentSemanticValue.Expression = new StringLiteral(ValueStack[ValueStack.Depth-1].Token.Value); CurrentSemanticValue.Expression.Location = CurrentLocationSpan; }
        break;
      case 50: // literal -> TRUE
{ CurrentSemanticValue.Expression = new BooleanLiteral(true); CurrentSemanticValue.Expression.Location = CurrentLocationSpan; }
        break;
      case 51: // literal -> FALSE
{ CurrentSemanticValue.Expression = new BooleanLiteral(false); CurrentSemanticValue.Expression.Location = CurrentLocationSpan; }
        break;
    }
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }


public Prog SyntaxTreeRoot { get; set; }

public Parser(Scanner scan) : base(scan)
{
}
}
}
